name: dotnet package

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '3.0', '3.1.x', '5.0.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Create Project
      run: dotnet new console --output RazorPagesMovie
    - name: Run Project
      run: dotnet run --project RazorPagesMovie
